name: PR Preview

on:
  pull_request:
    paths-ignore:
      - ".github/**"
      - ".vscode/**"

jobs:
  checks_and_tests:
    name: Linting, Type Check and Tests
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ Checkout Repo
        uses: actions/checkout@v3

      - name: ğŸ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: ğŸ Install dependencies
        run: npm install

      - name: ğŸ‘€ Check Linting
        run: npm run lint

      - name: ğŸ‘€ Check TypeScript
        if: ${{ success() }}
        run: npm run tsc

      - name: ğŸ‘€ Check Tests
        if: ${{ success() }}
        run: npm run test:coverage
